### ISSUE TITLE
The app asks to access internet: telemetry?

### ISSUE THREAD

**Issue by Tom4tot** [Armin2208/Windows-Auto-Night-Mode#11]
Hi, I've noticed today that using v1, the app tried to connect to the internet when switching theme. What's the reason behind that? 

(I could tell because my custom firewall notifies me when an app tries to access internet)

Thanks. :)

**Comment by Armin2208** [comment]
I didn't implemented any telemetry.
But the app accesses the internet at the App start to check for updates. But this shouldn't happen at theme switch. In 2.0 it also accesses the internet to get the name of the user city from the location (I think Microsoft Location APIs works with the internet). But also here: No access to the internet in the background.

I don't collect any telemetry. That's why I didn't even know how much people are using the app 😅

You can check the code in version 1.0. You will see that this version only edits one key if you start it with the argument /Dark or /light. 2.0 has much more lines of code there, but everything works offline.

Doesn't your custom firewall tell you what IP the program tries to reach? I know some firewalls doesn't tell that, but this would be helpful :D

Have a nice day.

**Comment by Armin2208** [comment]
Sure.

**Comment by Armin2208** [comment]
Update: While working on Version 2.1.1 I noticed that you are right. The application Always runs the main method, even if an Argument is used for startup. This means that on every theme switch a update-check is called.

I try to fix it. I Need to, because I currently have a big issue with it. This would also improve the efficiency.

**Comment by Armin2208** [comment]
Update: I now released Version 2.1.1. Please tell me, if your Firewall still Shows Messages when the theme gets switches in background.

**Comment by Tom4tot** [comment]
Hi, sorry for the late answer but it doesn't anymore. Only if I open the app (to check for updates i suppose). Thanks for fixing that. :)
