### ISSUE TITLE
Add automatic dark mode in Microsoft Office

### ISSUE THREAD

**Issue by VincentJoshuaET** [Armin2208/Windows-Auto-Night-Mode#24]
HKEY_CURRENT_USER\SOFTWARE\Microsoft\Office\16.0\Common\UI Theme value should just be also changed for automatic dark theme.

**Comment by Armin2208** [comment]
Sadly Office always reverts this Value back to the UserConfig.
I could block access, but when users can't change the theme anymore in the apps itself.

**Comment by xtprion** [comment]
Well, what if you give us another option, so since user know that they'll lose access to change theme via apps itself, they will have an option to use it or not.

**Comment by Armin2208** [comment]
@xtprion your are smart lol

**Comment by VincentJoshuaET** [comment]
Any update on this?

**Comment by Armin2208** [comment]
I never did something

**Comment by jpweytjens** [comment]
I would also like this option with the warning.

**Comment by jpweytjens** [comment]
Are you considering to add this option with the warning mentioned above?

**Comment by udobehm** [comment]
It was awesome if the office theme would change too. Maybe some more keys/code needs to be changed in order the theme will not only change but also stay till your app would change it again. What does the Office support say to this?? Can they help you (easily) implementing this function?

**Comment by udobehm** [comment]
Ok, I see. But thanks for investigating it!

**Comment by kcorax** [comment]
Just donated. More coming if you find a solution for this.

**Comment by Armin2208** [comment]
@kcorax you know how life works haha

**Comment by berot3** [comment]
Can't wait for this to happen! For me it doesn't make much sense to you your auto-switcher until office is not switching along too (sorry).

Also, I think there are quite a lot who are using office, especially in the office! 😃

**Comment by kcorax** [comment]
I'm afraid I've confirmed it's not possible though. Even if you intercept messages to the app. The only option would be to write directly in memmory like game trainers do, but that would be extremely fragile code. There's no point in encouraging a productivity app to crash for aesthetics.

**Comment by douglangille** [comment]
Is there something in this powershell script that might help? I hacked away at the scheduled tasks in ADM and made something workable based on this, but I have to deal with a PS window popping up. It'd be better in-app if at all possible.

https://www.cloudappie.nl/change-theme-officeproplus-powershell/

**Comment by Armin2208** [comment]
thanks for sharing @douglangille

**Comment by Armin2208** [comment]
> Is there something in this powershell script that might help? I hacked away at the scheduled tasks in ADM and made something workable based on this, but I have to deal with a PS window popping up. It'd be better in-app if at all possible.
> 
> https://www.cloudappie.nl/change-theme-officeproplus-powershell/

thanks to this site I was able to re-create the powershell as c# code. It works very well. Thanks again for sharing, 2.4 will bring Office theme switch! :)
BUT NO it's not possible to change the office theme while one program is running. You need to restart office to see the changes.

**Comment by Armin2208** [comment]
I updated the Beta release under releases. You can now test Office theme switch. Thank you!

**Comment by kcorax** [comment]
Donated as promised

**Comment by juhaszp95** [comment]
Hi There,

I think the Office theme switch still doesn't really work (it doesn't switch to night mode for sure - I'm using Office 365). However, you can set Office to set its theme according to the system mode. However, if I set that, that setting seems to go away / be overriden somehow by Auto Dark Mode. I wonder if I could prevent Auto Dark Mode from interfering with my Office setting, such that it would follow the system setting (set by Auto Dark Mode) effectively? (I see there is a "Microsoft Office (legacy)" switch on the Apps tab, but I'm not sure what that does if anything. It was set to "Adapt to system" so far.)

**Comment by Spiritreader** [comment]
> Hi There,
> 
> I think the Office theme switch still doesn't really work (it doesn't switch to night mode for sure - I'm using Office 365). However, you can set Office to set its theme according to the system mode. However, if I set that, that setting seems to go away / be overriden somehow by Auto Dark Mode. I wonder if I could prevent Auto Dark Mode from interfering with my Office setting, such that it would follow the system setting (set by Auto Dark Mode) effectively? (I see there is a "Microsoft Office (legacy)" switch on the Apps tab, but I'm not sure what that does if anything. It was set to "Adapt to system" so far.)

The office theme switch doesn't work for 365. It's only meant for older versions still carrying the year version number.

Two things you can try:

1) Set it to "let the app decide" and see if that works.

2) You can set it to "disabled" (as it should be for non-legacy office) and ADM will not modify the office theme registry keys anymore.
MS have changed the theme definitions for newer versions. Since those versions include a "follow system theme" option on their own. 

Sadly detecting the office versions are a bit convoluted, so the user has to make the correct decision on whether to tell Office to follow the system them or try the auto dark mode legacy implementation if the first option isn't available on their version.

**Comment by juhaszp95** [comment]
Many thanks! The ”let the app decide” mode seems to work for me (coupled with setting Office to follow the system theme).

 

Feladó: Sam ***@***.***> 
Küldve: 2023. február 10., péntek 22:46
Címzett: AutoDarkMode/Windows-Auto-Night-Mode ***@***.***>
Másolatot kap: juhaszp95 ***@***.***>; Comment ***@***.***>
Tárgy: Re: [AutoDarkMode/Windows-Auto-Night-Mode] Add automatic dark mode in Microsoft Office (#24)

 

Hi There,

I think the Office theme switch still doesn't really work (it doesn't switch to night mode for sure - I'm using Office 365). However, you can set Office to set its theme according to the system mode. However, if I set that, that setting seems to go away / be overriden somehow by Auto Dark Mode. I wonder if I could prevent Auto Dark Mode from interfering with my Office setting, such that it would follow the system setting (set by Auto Dark Mode) effectively? (I see there is a "Microsoft Office (legacy)" switch on the Apps tab, but I'm not sure what that does if anything. It was set to "Adapt to system" so far.)

The office theme switch doesn't work for 365. It's only meant for older versions still carrying the year version number.

Two things you can try:

1.	Set it to "let the app decide" and see if that works.
2.	You can set it to "disabled" (as it should be for non-legacy office) and ADM will not modify the office theme registry keys anymore.
MS have changed the theme definitions for newer versions. Since those versions include a "follow system theme" option on their own.

Sadly detecting the office versions are a bit convoluted, so the user has to make the correct decision on whether to tell Office to follow the system them or try the auto dark mode legacy implementation if the first option isn't available on their version.
