### ISSUE TITLE
Changing the theme with the right-click actions on the app's jump list doesn't change the desktop wallpaper

### ISSUE THREAD

**Issue by 19lmyers** [Armin2208/Windows-Auto-Night-Mode#29]
Noticed this in 2.2.

**Comment by Armin2208** [comment]
Hello.

It does switch. But only after closing the main window for the first time, because when the app saved the config.
Switching the theme from the Taskbar creates a new instance of the app. And this instance doesn't know anything about your custom background until you didn't close the main window.

try that again and tell me if it's working for you.

**Comment by 19lmyers** [comment]
Oh, it's working now. Thanks!
