### ISSUE TITLE
Start menu tile color

### ISSUE THREAD

**Issue by MaxVonMustermann** [Armin2208/Windows-Auto-Night-Mode#34]
Please add the ability to alter the start menu tile color to be the same as the current OS accent color. I don't really like the black that came with the new version, since it destroys consistency for my start menu. So adding the ability to change it to accent color would be great.
Thanks for the work on this useful program! :)

**Comment by Armin2208** [comment]
Hello,

open your start menu -> right click on auto dark mode -> more -> open file location.
An Explorer window opens with the shortcut of auto dark mode marked. Right click on the stortcut and choose again open file location in the context menu. Now you are in the install directory of Auto Dark Mode.
There you just need to delete the file AutoDarkMode.VisualElementsManifest.xml.

I can't make the tile transparent, but I also don't want that the program name is displayed on the tile. That's why I will not change this atm.
