### ISSUE TITLE
Black text on dark background: Use Windows' Custom color scheme as the Light Mode

### ISSUE THREAD

**Issue by anohren** [Armin2208/Windows-Auto-Night-Mode#76]
If I want accent colors in the taskbar in combination with light mode for apps, then I cannot use Auto Night Mode even though it supports "Always dark" for System. If I enable that, I get a taskbar with my dark accent color, but also a taskbar with black text. The text is no longer legible, because as far as Windows is concerned the color scheme is "Light" and should therefore use black text.

As a solution, would it be possible to instead of the app treating Windows' "Light" color setting as the Light Mode, let the app treat Windows' "Custom" color setting as the Light Mode? That way Windows won't be confused by a dark taskbar when the color scheme is set to Light, and we can get the correct white text on dark background.

**Comment by Armin2208** [comment]
I don't get it.

Accent color on white Taskbar isn't supported at all from windows. This isn't possible.

Taskbar needs to be dark. This is why you set Taskbar to always dark and don't set it anymore to light.

And why you have now dark text on a dark Taskbar? Because your accent color is too dark?

**Comment by anohren** [comment]
> Accent color on white Taskbar isn't supported at all from windows. This isn't possible.

Sorry, not entirely sure what you mean. I can set the color scheme in Windows to Light, Dark or Custom. Custom allows me to have light apps and a dark start menu and taskbar. The accent color can then be enabled, which gives the entire taskbar the color that you've set as accent color.

> Taskbar needs to be dark. This is why you set Taskbar to always dark and don't set it anymore to light.

Yes. This can be done only in Windows' Custom color scheme if you want the applications to remain light and not dark.

> And why you have now dark text on a dark Taskbar? Because your accent color is too dark?

Because as soon as I use Auto Dark Mode to change from Dark Mode to Light Mode, Windows' color scheme changes from Dark to Light (which can be confirmed in system settings) which in turn prompts Windows to change the text in the taskbar from white to black.

I'll add a picture next time I boot into Windows.

**Comment by Armin2208** [comment]
In auto dark mode you can choose if it should only change apps, or also system. And you can set the checkbox to use accent color on Taskbar.
Everything is integrated :)

**Comment by alsitko** [comment]
I ran into this issue myself:
With Auto-Night-Mode enabled, the color of the task bar itself behaves correctly, but the clock and the icons do not:
I do have a brownish colour as my accent colour, so I need to have white icons, which works perfectly well when switching directly via Windows itself. 
When using AutoNightMode to switch modes, during daytime the icons on the taskbar are not white as expected, they are black and thus pretty hard to see.
It would be great if you could fix that issue.

**Comment by anohren** [comment]
I tested this some more. While the bug exists, it seems to have disappeared after a reboot, after having enabled _System: Always dark_ and _Accent Color for Taskbar_ in the app.

If not beacuse of the reboot, then perhaps something else changed that I'm not aware of. But the fact is that the app now behaves exactly like how I proposed; it changes between Windows' Dark and Custom color schemes instead of between Dark and Light.

**Comment by Spiritreader** [comment]
I have encountered this issue while reimplementing the color prevalence logic in v3.

Even though accent color isn't supported when the system is in light mode, it is still possible to set the registry key which will then re-enable the accent color nonetheless, resulting in dark icons on a colored taskbar.

I've noticed that if you switch the theme via the Windows control panel it just disables color prevalence beforehand, while also somehow **always refreshing text and icons**. If color prevalence is not updated correctly, it will kind of cause undefined behavior where text and icons might remain dark/light when they shouldn't.

The current stable version of AutoDarkMode should already take care of this by using a delay. However I've experienced issues with the delay of 200ms being too short, so this might be where things go south for you.

In any case, this should hopefully be fixed in v3.

### Logic in v3:

The correct behavior with color prevalence (accent color) enabled is, as in current stable, as follows:

**Switch from dark to light mode:**
Disable color prevalence, then switch to light

**Switch from light to dark mode:**
Switch to dark mode, then enable color prevalence.

It will use a delay of 400ms and run the system switching logic in its own thread for responsiveness.
In case there are more users experiencing issues it might be a good idea to introduce a user configurable delay in case a system taskes longer to perform the switch.

**Comment by Spiritreader** [comment]
This should also be fixed in version 3 and up.

**Comment by anohren** [comment]
Nice work!
